/**
 * AgentHub v3 — Wallet Setup Script
 * Creates two Stellar testnet wallets (Client + Service Provider),
 * funds them with XLM via Friendbot, and creates USDC trustlines.
 * 
 * After running this, you MUST manually fund USDC via:
 * https://faucet.circle.com (select Stellar Testnet)
 */
import { Keypair, Horizon, TransactionBuilder, Networks, Operation, Asset } from "@stellar/stellar-sdk";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.join(__dirname, "../.env");

// Stellar Testnet USDC issuer (Circle)
const USDC_ISSUER = "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5";
const USDC_ASSET = new Asset("USDC", USDC_ISSUER);

const server = new Horizon.Server("https://horizon-testnet.stellar.org");

async function fundWithFriendbot(publicKey) {
  const res = await fetch(`https://friendbot.stellar.org?addr=${encodeURIComponent(publicKey)}`);
  if (!res.ok) throw new Error(`Friendbot failed for ${publicKey}`);
  console.log(`  ✅ Funded ${publicKey.slice(0, 8)}... with testnet XLM`);
}

async function createUsdcTrustline(secretKey) {
  const keypair = Keypair.fromSecret(secretKey);
  const account = await server.loadAccount(keypair.publicKey());
  
  const tx = new TransactionBuilder(account, {
    fee: "100000",
    networkPassphrase: Networks.TESTNET,
  })
    .addOperation(Operation.changeTrust({ asset: USDC_ASSET }))
    .setTimeout(30)
    .build();

  tx.sign(keypair);
  await server.submitTransaction(tx);
  console.log(`  ✅ USDC trustline created for ${keypair.publicKey().slice(0, 8)}...`);
}

async function main() {
  console.log("\n🚀 AgentHub v3 — Wallet Setup\n");

  // Generate Client Wallet (MCP server uses this to pay for services)
  const clientKeypair = Keypair.random();
  console.log("📱 Client Agent Wallet (pays for x402 services):");
  console.log(`  Public:  ${clientKeypair.publicKey()}`);
  console.log(`  Secret:  ${clientKeypair.secret()}`);

  // Generate Service Provider Wallet (receives payments from x402 tools)
  const providerKeypair = Keypair.random();
  console.log("\n🏪 Service Provider Wallet (receives USDC from tool payments):");
  console.log(`  Public:  ${providerKeypair.publicKey()}`);
  console.log(`  Secret:  ${providerKeypair.secret()}`);

  // Fund both with XLM
  console.log("\n💰 Funding wallets with testnet XLM...");
  await fundWithFriendbot(clientKeypair.publicKey());
  await fundWithFriendbot(providerKeypair.publicKey());

  // Create USDC trustlines
  console.log("\n🔗 Creating USDC trustlines...");
  await createUsdcTrustline(clientKeypair.secret());
  await createUsdcTrustline(providerKeypair.secret());

  // Write to .env
  const envContent = `# AgentHub v3 Configuration
# Generated by setup-wallets.js

# Venice AI (Smart Router / Orchestrator)
VENICE_API_KEY=${process.env.VENICE_API_KEY || "PASTE_YOUR_VENICE_KEY_HERE"}

# GitHub API Token (for github-auditor service)
GITHUB_TOKEN=${process.env.GITHUB_TOKEN || "PASTE_YOUR_GITHUB_TOKEN_HERE"}

# Client Agent Wallet (MCP server pays x402 services from this wallet)
STELLAR_CLIENT_SECRET=${clientKeypair.secret()}
STELLAR_CLIENT_PUBLIC=${clientKeypair.publicKey()}

# Service Provider Wallet (x402 tool servers receive USDC here)
STELLAR_PROVIDER_SECRET=${providerKeypair.secret()}
STELLAR_PROVIDER_PUBLIC=${providerKeypair.publicKey()}

# x402 Network Configuration
STELLAR_NETWORK=stellar:testnet
STELLAR_RPC_URL=https://soroban-testnet.stellar.org
X402_FACILITATOR_URL=https://www.x402.org/facilitator
`;

  fs.writeFileSync(envPath, envContent);
  console.log("\n📝 Written to .env");

  console.log("\n" + "=".repeat(60));
  console.log("⚠️  IMPORTANT: You must now fund both wallets with testnet USDC!");
  console.log("   1. Go to https://faucet.circle.com");
  console.log("   2. Select 'Stellar Testnet' from the network dropdown");
  console.log(`   3. Paste CLIENT address:  ${clientKeypair.publicKey()}`);
  console.log(`   4. Paste PROVIDER address: ${providerKeypair.publicKey()}`);
  console.log("   5. Request USDC for both");
  console.log("=".repeat(60) + "\n");
}

main().catch(console.error);
